typography_spectrum: 0.09855406451970339
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.31219322932884097
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.26142
analytics:
  google: null
  facebook: null
  twitter: null
name: thinkmortgage
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Our Mortgage Services are FREE! We are Paid by the LENDER!
description: 'We work for you, not the lender!'
purpose: []
